name             'wordpress-rean'
maintainer       'Andy Boutte'
maintainer_email 'andyboutte@mac.com'
license          'All rights reserved'
description      'Installs/Configures wordpress-rean'
long_description 'Installs/Configures wordpress-rean'
version          '0.1.0'

depends 'wordpress'
depends 'chef_hostname'
depends 'users'