name             'cms-rean'
maintainer       'Andy Boutte'
maintainer_email 'andyboutte@mac.com'
license          'All rights reserved'
description      'Installs/Configures cms-rean'
long_description 'Installs/Configures cms-rean'
version          '0.1.0'

depends 'wordpress'
depends 'chef_hostname'
depends 'users'
depends 'wp-cli'
depends 'sudo'